- id: check-commit-msg
  name: check commit message
  entry: check-commit-msg
  description: 检查提交内容是否符合规范
  language: python
  stages: [commit-msg]
- id: check-linebreak
  name: check linebreak
  entry: check-linebreak
  description: 检查换行符是否为LF
  language: python
  types: [text]
- id: check-utf8
  name: check utf8
  entry: check-utf8
  description: 检查文件是否为UTF-8编码
  language: python
  types: [text]
- id: check-version
  name: check version
  entry: check-version
  description: 检查版本号是否正确（提交信息与版本文件匹配，版本号递增合法）
  language: python
  stages: [commit-msg]
